### PR TITLE
DOT minor changes

### PR DESCRIPTION
**Pull request by NaveenElumalaiAMD**
Made some changes to the comments in dot.cpp file

### CODE REVIEW

**Comment by daineAMD** [comment]
Not that it's a big deal for this repo, but I added the noCI label since this is only comment changes.

**Comment by TorreZuk** [comment]
> Not that it's a big deal for this repo, but I added the noCI label since this is only comment changes.

Daine I would think we shouldn't use noCI for doc changes inside the code otherwise formatting and accidental code changes won't get caught.  no?

**Comment by daineAMD** [comment]
Hm, maybe. Since the CI group added the static analysis job, I wonder if we're still planning on running format checks for noCI PRs? As for accidental code changes, that's fair, but if this were a rocBLAS job I would still be tempted to use noCI since I think. I suppose it can be up to reviewer's/developers discretion :)

**Comment by NaveenElumalaiAMD** [comment]
Hey Daine, would it be okay to remove the noci label?  In my initial commit, i did not do a clang formatting to the .cpp file and did a pull request. Then, i figured out i had to do the clang formatting to the .cpp file and tried to add the file  again and i got a reply that it's up to date. Therefore, I think it is okay to merge this .cpp file with noci label. But, Just to be on the safer side i want to run the CI tests too. Is that okay for you?

**Comment by NaveenElumalaiAMD** [comment]
Thanks Daine

**Pull request merged**
