### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by NaveenElumalaiAMD**

### CODE REVIEW

**Review by TorreZuk — COMMENTED** [review]
Is this the same as rocblas client?  i.e. how is complex handled on windows?

**Comment by TorreZuk** [comment]
> > Is this the same as rocblas client? i.e. how is complex handled on windows?
> 
> In rocBLAS client, we do initialize this way std::complex arr[i] = T((float)rval); where the imaginary part of the complex number will be automatically assigned to zeros. I think you introduced different methods of initialization for this helper function `fillVectorUniformIntRand` do you recall why this was added?

We have overrides for complex to set real and imaginary both random so not sure of the std::complex use case, I can check rocblas-client.    Anyway fine for this example to be fixed with this PR, but should get windows setting both components the same as linux, windows should not be different unless a specific limitation.

**Review by TorreZuk — APPROVED** [review]
Fix passes, still want windows to match linux if possible.  Future work is fine.

**Comment by NaveenElumalaiAMD** [comment]
Created a ticket here to address this here: [LWPMLSE-467](https://ontrack-internal.amd.com/browse/LWPMLSE-467).

**Pull request merged**
